### ISSUE TITLE
"hey Bob"

### ISSUE THREAD

**Issue by KevinSwitzer** [gmeyerflvs/cfBatchValidator#1]
Line 4 just says "hey Bob"
This causes an error.

**Comment by gmeyerflvs** [comment]
validation error or PHP error? Details needed please.

**Comment by KevinSwitzer** [comment]
lol... validation error, although it doesn't honestly matter. Just delete line 4 and you're set.

**Comment by KevinSwitzer** [comment]
Apparently github didn't link that the issue is in config.php.

**Comment by gmeyerflvs** [comment]
I'm still confused. I looked at config.php and see nothing out of the ordinary. If you have a validation error, then that is a validation engine item.

**Comment by gmeyerflvs** [comment]
found in repo extraneous text. Removed and committed.

**Comment by gmeyerflvs** [comment]
issue fixed in repo
